name: CI

on:
  push:
    branches: main

jobs:
  compile:
    runs-on: ubuntu:22.04
    steps:
      - name: Checkout code
        uses: actions/checkout/@v3

      - name: Set up JDK 21
        uses: actions/setup-java/@v2
        with:
          java-version: "21"

      - name: Compile code
        run: ./gradlew assemble

  test:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: "21"

      - name: Run unit tests
        run: ./gradlew test

  generate_artifact:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate artifact
        run: ./gradlew build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: the-artifact
          path: artifact

  store_artifact:
    runs-on: ubuntu-latest
    needs: generate_artifact
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: the-artifact
          path: artifact
